import { fmtDate } from '../utils/format.utils.js';

/**
 * MakerWorld listing draft export.
 * Generates a Markdown file ready for copy-paste into MakerWorld's listing form.
 */

export function generateMakerWorldListing(brief, metadata) {
  const partType = metadata?.partType || 'Part';
  const objectType = brief?.object_type || partType;
  const material = brief?.material_recommendation || 'PLA';
  const printStrategy = brief?.print_strategy || {};
  const dims = metadata?.dimensions || brief?.dimensions || {};
  const volume = metadata?.volume || 0;
  const mass = metadata?.estimatedMass || 0;
  const infill = printStrategy.infill || 20;
  const supports = printStrategy.supports ? 'Yes' : 'No';

  const tags = [
    partType, material, 'functional', '3d-print', 'parametric', 'FDM',
    ...(brief?.features || []).slice(0, 5)
  ].join(', ');

  return `# ${objectType}

> Generated by **Micas v2** — AI-assisted parametric design
> Date: ${fmtDate(Date.now())}

---

## Description

${brief?.reasoning || `A ${objectType} designed for FDM 3D printing. Parametric design with clean geometry for reliable printing.`}

---

## Print Settings

| Setting           | Value             |
|-------------------|-------------------|
| **Material**      | ${material}       |
| **Layer Height**  | 0.2 mm            |
| **Infill**        | ${infill}%        |
| **Supports**      | ${supports}       |
| **Perimeters**    | 3                 |

---

## Dimensions

${Object.entries(dims).filter(([,v]) => v != null && typeof v === 'number').map(([k, v]) => `- **${k}**: ${v.toFixed(1)} mm`).join('\n') || '- See STL file for dimensions'}

- **Estimated Volume**: ${(volume / 1000).toFixed(1)} cm³
- **Estimated Mass**: ${mass.toFixed(1)} g (${material})

---

## Features

${(brief?.features || ['FDM-printable', 'Parametric design']).map(f => `- ${f}`).join('\n')}

---

## Assembly

${(brief?.constraints || []).length > 0
  ? (brief.constraints || []).map(c => `- ${c}`).join('\n')
  : '- No assembly required — single-piece print'}

---

## Tags

${tags}

---

*This listing was drafted by Micas v2 — edit before publishing.*
`;
}
