/**
 * OpenSCAD code generation helpers.
 * All functions return OpenSCAD code strings.
 *
 * Usage: import { cube, cylinder, difference, ... } from './openscad-writer.js'
 */

const VERSION_COMMENT = '// Generated by Micas v2\n// Edit the parameters at the top to customize.\n';

export function header(partName = 'Part', params = {}) {
  const paramLines = Object.entries(params)
    .map(([k, v]) => `${k} = ${JSON.stringify(v)};`)
    .join('\n');
  return `${VERSION_COMMENT}// Part: ${partName}\n// Generated: ${new Date().toISOString()}\n\n${paramLines}\n\n`;
}

export function cube(w, d, h, centered = true) {
  return `cube([${fmt(w)}, ${fmt(d)}, ${fmt(h)}], center=${centered});`;
}

export function cylinder(r, h, fn = 32, centered = true) {
  return `cylinder(r=${fmt(r)}, h=${fmt(h)}, $fn=${fn}, center=${centered});`;
}

export function cylinderRH(r1, r2, h, fn = 32) {
  return `cylinder(r1=${fmt(r1)}, r2=${fmt(r2)}, h=${fmt(h)}, $fn=${fn});`;
}

export function sphere(r, fn = 32) { return `sphere(r=${fmt(r)}, $fn=${fn});`; }

export function translate(v, child) {
  return `translate([${v.map(fmt).join(', ')}])\n  ${indent(child)}`;
}

export function rotate(v, child) {
  return `rotate([${v.map(fmt).join(', ')}])\n  ${indent(child)}`;
}

export function scaleOp(v, child) {
  return `scale([${v.map(fmt).join(', ')}])\n  ${indent(child)}`;
}

export function mirror(v, child) {
  return `mirror([${v.map(fmt).join(', ')}])\n  ${indent(child)}`;
}

export function difference(children) {
  return `difference() {\n${children.map(c => '  ' + indent(c)).join('\n')}\n}`;
}

export function union(children) {
  return `union() {\n${children.map(c => '  ' + indent(c)).join('\n')}\n}`;
}

export function intersection(children) {
  return `intersection() {\n${children.map(c => '  ' + indent(c)).join('\n')}\n}`;
}

export function linearExtrude(height, child, { twist = 0, slices = 20, scale = 1 } = {}) {
  return `linear_extrude(height=${fmt(height)}, twist=${twist}, slices=${slices}, scale=${scale})\n  ${indent(child)}`;
}

export function rotateExtrude(angle = 360, child, fn = 64) {
  return `rotate_extrude(angle=${angle}, $fn=${fn})\n  ${indent(child)}`;
}

export function polygon(points, paths = null) {
  const pts = points.map(([x, y]) => `[${fmt(x)}, ${fmt(y)}]`).join(', ');
  if (paths) {
    const pth = paths.map(p => `[${p.join(', ')}]`).join(', ');
    return `polygon(points=[${pts}], paths=[${pth}]);`;
  }
  return `polygon(points=[${pts}]);`;
}

export function module(name, paramNames, body) {
  return `module ${name}(${paramNames.join(', ')}) {\n${body.split('\n').map(l => '  ' + l).join('\n')}\n}`;
}

export function call(name, args = {}) {
  const argStr = Object.entries(args).map(([k, v]) => `${k}=${JSON.stringify(v)}`).join(', ');
  return `${name}(${argStr});`;
}

export function comment(text) {
  return `// ${text}`;
}

export function forLoop(variable, range, child) {
  return `for (${variable} = [${range[0]}:${range[1]}:${range[2]}]) {\n  ${indent(child)}\n}`;
}

// Helpers
function fmt(n) {
  if (typeof n === 'boolean') return String(n);
  return Number.isInteger(n) ? String(n) : n.toFixed(4);
}

function indent(code) {
  return code.split('\n').join('\n  ');
}

/** Build a complete .scad file */
export function buildSCADFile(partName, paramObj, bodyCode) {
  return header(partName, paramObj) + bodyCode;
}
